//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genesis.Recursos_localizables {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Genesis.Recursos_localizables.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administración.
        /// </summary>
        internal static string SistemaMenuItemAdministracion {
            get {
                return ResourceManager.GetString("SistemaMenuItemAdministracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administración de beneficios.
        /// </summary>
        internal static string SistemaMenuItemAdministracionDeBeneficios {
            get {
                return ResourceManager.GetString("SistemaMenuItemAdministracionDeBeneficios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administración de equipos.
        /// </summary>
        internal static string SistemaMenuItemAdministracionDeEquipos {
            get {
                return ResourceManager.GetString("SistemaMenuItemAdministracionDeEquipos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administración de familias.
        /// </summary>
        internal static string SistemaMenuItemAdministracionDeFamilias {
            get {
                return ResourceManager.GetString("SistemaMenuItemAdministracionDeFamilias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administración de grupos.
        /// </summary>
        internal static string SistemaMenuItemAdministracionDeGrupos {
            get {
                return ResourceManager.GetString("SistemaMenuItemAdministracionDeGrupos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administración de objetivos.
        /// </summary>
        internal static string SistemaMenuItemAdministracionDeObjetivos {
            get {
                return ResourceManager.GetString("SistemaMenuItemAdministracionDeObjetivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administración de usuarios.
        /// </summary>
        internal static string SistemaMenuItemAdministracionDeUsuarios {
            get {
                return ResourceManager.GetString("SistemaMenuItemAdministracionDeUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Beneficio por empleado.
        /// </summary>
        internal static string SistemaMenuItemBeneficioPorEmpleado {
            get {
                return ResourceManager.GetString("SistemaMenuItemBeneficioPorEmpleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bitacora.
        /// </summary>
        internal static string SistemaMenuItemBitacora {
            get {
                return ResourceManager.GetString("SistemaMenuItemBitacora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Evaluación.
        /// </summary>
        internal static string SistemaMenuItemEvaluacion {
            get {
                return ResourceManager.GetString("SistemaMenuItemEvaluacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Evaluar equipos a cargo.
        /// </summary>
        internal static string SistemaMenuItemEvaluarEquiposACargo {
            get {
                return ResourceManager.GetString("SistemaMenuItemEvaluarEquiposACargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        internal static string SistemaMenuItemIdioma {
            get {
                return ResourceManager.GetString("SistemaMenuItemIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mi estado.
        /// </summary>
        internal static string SistemaMenuItemMiEstado {
            get {
                return ResourceManager.GetString("SistemaMenuItemMiEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Objetivos por empleado.
        /// </summary>
        internal static string SistemaMenuItemObjetivosPorEmpleados {
            get {
                return ResourceManager.GetString("SistemaMenuItemObjetivosPorEmpleados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Objetivos por equipo.
        /// </summary>
        internal static string SistemaMenuItemObjetivosPorEquipo {
            get {
                return ResourceManager.GetString("SistemaMenuItemObjetivosPorEquipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Realizar Back Up.
        /// </summary>
        internal static string SistemaMenuItemRealizarBackUp {
            get {
                return ResourceManager.GetString("SistemaMenuItemRealizarBackUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Realizar restore.
        /// </summary>
        internal static string SistemaMenuItemRealizarRestore {
            get {
                return ResourceManager.GetString("SistemaMenuItemRealizarRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reportes.
        /// </summary>
        internal static string SistemaMenuItemReportes {
            get {
                return ResourceManager.GetString("SistemaMenuItemReportes", resourceCulture);
            }
        }
    }
}
